# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expens',
            new_name='Expense',
        ),
    ]
